/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooRelBWRunningWidth.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooRelBWRunningWidth) 

 RooRelBWRunningWidth::RooRelBWRunningWidth(const char *name, const char *title, 
                        RooAbsReal& _mww,
                        RooAbsReal& _mH,
                        RooAbsReal& _gamma) :
   RooAbsPdf(name,title), 
   mww("mww","mww",this,_mww),
   mH("mH","mH",this,_mH),
   gamma("gamma","gamma",this,_gamma)
 { 
 } 


 RooRelBWRunningWidth::RooRelBWRunningWidth(const RooRelBWRunningWidth& other, const char* name) :  
   RooAbsPdf(other,name), 
   mww("mww",this,other.mww),
   mH("mH",this,other.mH),
   gamma("gamma",this,other.gamma)
 { 
 } 



 Double_t RooRelBWRunningWidth::evaluate() const 
 { 

	 Double_t numerator = (mww*mww*gamma/mH) ;
	 Double_t denominator = (mww*mww-mH*mH)*(mww*mww-mH*mH) + (mww*mww*gamma/mH)*(mww*mww*gamma/mH);
	 Double_t pdf = numerator/denominator;
	 return pdf;

 } 



